### ISSUE TITLE
[Voting] Name of the base repository

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/core#522]
Hey all,

as @stonemaster has recently moved this repository to the dlang-tour organization, we have the moral obligation to find a suited name ;-)
To avoid bike-sheding, this issue can be used to post suggestions and vote for them. A couple of rules:
- only _one_ name per comment (see my examples below)
- voting is done with the thumbs-up button of GH
- you can vote for as many names as you like

We will give this enough time, s.t. everyone has a fair chance to propose names and vote, so the decision will be made based on a majority-vote on Thursday next week (2017-06-08).

Happy voting :+1:

**Comment by wilzbach** [comment]
base

**Comment by wilzbach** [comment]
core

**Comment by wilzbach** [comment]
server

**Comment by wilzbach** [comment]
core-web (credit to @ZombineDev)

**Comment by llucenic** [comment]
tour-web

**Comment by WebFreak001** [comment]
vote for keeping the old name

**Comment by wilzbach** [comment]
core & core-rdmd it's then. Thanks a lot @ all for participating!
