### ISSUE TITLE
Allow specifying program arguments

### ISSUE THREAD

**Issue by CyberShadow** [dlang-tour/core#546]
Needed for dlang.org runnable examples and DPaste feature parity.

**Comment by wilzbach** [comment]
Do you also want to be able to pass in program arguments? Or did you only refer to compiler arguments?

**Comment by CyberShadow** [comment]
Program arguments, as on DPaste.

Ideally compiler options should be presented as checkboxes or such, and translated to the chosen compiler's command-line syntax.

**Comment by wilzbach** [comment]
I finally got around adding this to the API: https://github.com/dlang-tour/core/pull/619
(the Docker images support this for quite a while).
