### ISSUE TITLE
Allow specifying program input (stdin)

### ISSUE THREAD

**Issue by CyberShadow** [dlang-tour/core#547]
Needed for dlang.org runnable examples and DPaste feature parity.

**Comment by wilzbach** [comment]
A first proposal: https://github.com/dlang-tour/core-rdmd/pull/9

**Comment by CyberShadow** [comment]
Implementing this will allow closing https://issues.dlang.org/show_bug.cgi?id=15178

**Comment by wilzbach** [comment]
I finally got around adding this to the API: https://github.com/dlang-tour/core/pull/619
(the Docker images support this for quite a while).

**Comment by wilzbach** [comment]
Deployed.
