### ISSUE TITLE
Allow saving code snippets in the playground

### ISSUE THREAD

**Issue by CyberShadow** [dlang-tour/core#548]
Needed for DPaste feature parity.

It would be preferable to use an identifier scheme that's compatible with DPaste's, so that DPaste's database can be migrated to the tour's playground.

**Comment by wilzbach** [comment]
We could simply save them to GitHub gists and do sth. like `https://tour.dlang.org/editor/g/<id>` (with will fetch the first file of the gist on load.

> It would be preferable to use an identifier scheme that's compatible with DPaste's, so that DPaste's database can be migrated to the tour's playground.

We could auto export all of them to Gists and then save a mapping, s.t. a simple redirect script can forward people.

**Comment by CyberShadow** [comment]
> We could auto export all of them to Gists

Not going to work.

1. There are currently 10786 pastes on DPaste
2. A lot of them are spam
3. Even 1-2 magnitudes fewer pastes, GitHub is likely not going to be happy about mass-dumping stuff to Gist.

**Comment by wilzbach** [comment]
> Even 1-2 magnitudes fewer pastes, GitHub is likely not going to be happy about mass-dumping stuff to Gist.

Hmm, we could use a separate, authenticated account for this mass-dump.
Do you have a better idea? Is generating short urls with is.gd good enough?
I would be very happy if we don't need to maintain a modifiable database here - this just brings a lot of troubles with maintenance (spam, hard drive limit, more complicated dev setup, ...)

**Comment by CyberShadow** [comment]
> Hmm, we could use a separate, authenticated account for this mass-dump.

I don't see how that changes anything.

> Is generating short urls with is.gd good enough?

I don't understand how that would solve anything.

> I would be very happy if we don't need to maintain a modifiable database here - this just brings a lot of troubles with maintenance (spam, hard drive limit, more complicated dev setup, ...)

Spam is not a problem because there is no "list of all pastes". Hard drive space is not a problem by empirical observation - DPaste's front end MySQL directory is only 180MB so far.

> Do you have a better idea?

Dedicated redirect service with a read-only database? Accept DPaste URLs, and redirect to the tour's editor page with the full code in the URL. Not sure if that's going to hit any header or URL length limits though...
