### ISSUE TITLE
Support choosing D compiler in the playground

### ISSUE THREAD

**Issue by CyberShadow** [dlang-tour/core#549]
Needed for DPaste feature parity (and, in some cases, for dlang.org runnable examples).

Would be nice to support:
- current DMD stable
- current DMD nightly
- GDC and/or LDC

**Comment by wilzbach** [comment]
- DMD beta
- LDC beta

**Comment by wilzbach** [comment]
Instead of building our our docker images, we could also look into reusing these:

https://hub.docker.com/r/dlanguage/ldc/
https://hub.docker.com/u/dlanguage/

**Comment by wilzbach** [comment]
I started to fork https://github.com/dlang-tour/core-rdmd and play a bit with it (-> https://github.com/dlang-tour/core-exec). It's still in testing, but the following already works:

```bash
docker run --rm dlangtour/core-exec:dmd-nightly $(echo 'void main() { import std.stdio; writeln("Hello World",  __VERSION__, __VENDOR__); }' | base64 -w0)
docker run --rm dlangtour/core-exec:ldc-beta $(echo 'void main() { import std.stdio; writeln("Hello World",  __VERSION__, __VENDOR__); }' | base64 -w0)
```

Travis is configured
- to push the built images to Dockerhub: https://hub.docker.com/r/dlangtour/core-exec/tags/
- to run daily - i.e. update these Docker images daily :)

I will from now on use PRs to this repo.

**Comment by ZombineDev** [comment]
It's alive! 🎊 
![its_alive](https://user-images.githubusercontent.com/3475150/27965235-c777eece-6343-11e7-8232-3b884460df95.PNG)

**Comment by wilzbach** [comment]
There's a separate issue to track the issue with gdc + perl, so closing this :)
