### ISSUE TITLE
Use dlang.org theme on the editor page

### ISSUE THREAD

**Issue by CyberShadow** [dlang-tour/core#550]
Currently the editor page is pretty bare-bones:

https://tour.dlang.org/editor

Would be nice to use the dlang.org theme, at least for the top navigation bar.

**Comment by wilzbach** [comment]
The tour already has a copy of the Dlang navigation bar (e.g. https://tour.dlang.org)

I actually actively disabled it actively (https://github.com/dlang-tour/core/blob/master/views/base.dt#L16). Do you simply want the same navigation as on dlang.org?

**Comment by CyberShadow** [comment]
Well, currently the page is completely devoid of branding, so it's not clear if it's a third-party website or if it's affiliated with dlang.org. Making it look like it's part of the network would be nice.

A very similar case is the forum, which uses dlang.org's navigation bar mostly verbatim.

**Comment by wilzbach** [comment]
> A very similar case is the forum, which uses dlang.org's navigation bar mostly verbatim.

Fair enough, shouldn't be hard then.
-> https://github.com/dlang-tour/core/pull/553
