### ISSUE TITLE
Editor page not using full width

### ISSUE THREAD

**Issue by CyberShadow** [dlang-tour/core#551]
[Example](https://tour.dlang.org/editor?source=void%20main()%0A%7B%0A%20import%20std.array%3B%0A%20import%20std.stdio%3A%20write%2C%20writeln%2C%20writef%2C%20writefln%3B%0A%20import%20std.range%3B%0A%20import%20std.typecons%3B%0A%20auto%20a%20%3D%20assocArray(zip(%5B0%2C%201%2C%202%5D%2C%20%5B%22a%22%2C%20%22b%22%2C%20%22c%22%5D))%3B%20%2F%2F%20aka%20zipMap%0A%20assert(is(typeof(a)%20%3D%3D%20string%5Bint%5D))%3B%0A%20writeln(a)%3B%20%2F%2F%20%5B0%3A%22a%22%2C%201%3A%22b%22%2C%202%3A%22c%22%5D%0A%20%0A%20auto%20b%20%3D%20assocArray(%5B%20tuple(%22foo%22%2C%20%22bar%22)%2C%20tuple(%22baz%22%2C%20%22quux%22)%20%5D)%3B%0A%20assert(is(typeof(b)%20%3D%3D%20string%5Bstring%5D))%3B%0A%20writeln(b)%3B%20%2F%2F%20%5B%22foo%22%3A%22bar%22%2C%20%22baz%22%3A%22quux%22%5D%0A%7D). There should be no line wrapping when the browser window is wide enough.

**Comment by wilzbach** [comment]
This is already fixed in https://github.com/dlang-tour/core/pull/545

**Comment by CyberShadow** [comment]
That doesn't seem like the right issue # ?

**Comment by wilzbach** [comment]
> That doesn't seem like the right issue # ?

Yep sorry.
-> https://github.com/dlang-tour/core/pull/544

**Comment by CyberShadow** [comment]
Actually I noticed that this issue is reproducible on Firefox but not on Chromium, like #552. So, just to clarify, a screenshot:

![](https://dump.thecybershadow.net/604d7fa9e23fd98af23a78865a008792/18%3A19%3A49-upload.png)

**Comment by wilzbach** [comment]
#544 has been merged, so this should be fixed.
