### ISSUE TITLE
open in dpaste

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/core#56]
I heard that the dpaste service will be reworked soon and is supposed to be a lot faster & get more features.
So maybe a button "open in dpaste" could be helpful for readers that want to continue the example their?

Ping @CyberShadow

**Comment by CyberShadow** [comment]
Forwarding the ping to @nazriel :)

**Comment by nazriel** [comment]
Thanks for the ping.

I am all for that of course.
Maybe we could also add another backend using dpaste alongside the "stupidlocal" and "docker".
Dpaste used to be rather hardened well.

Btw - this project is super awesome - I just saw it recently. Wish I knew it before when talking about D @ company 👍

**Comment by stonemaster** [comment]
@nazriel Thanks a lot!
I have also though about dpaste integration as a driver for running the examples. I'll create another issue for that. It might really make sense depending on how the current Docker driver will scale when the tour is really used in production..

**Comment by wilzbach** [comment]
> I am all for that of course.

@nazriel do you have an API that we could use? I guess the only way is that we (or the client via CORS) sends you a POST request and you reply with the URL to the newly created DPaste? Or do you have a better idea?

Using GET would be a lot simpler, but this sadly has a restriction of 2K chars.

http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by wilzbach** [comment]
> @nazriel do you have an API that we could use? I guess the only way is that we (or the client via CORS) sends you a POST request and you reply with the URL to the newly created DPaste? Or do you have a better idea?

Ping @nazriel 

I think we can hack something together with the undocumented API at http://dlang.org/js/run.js, but two quick questions here:
1) AFAIK you still plan to rewrite DPaste? -> would the API be the same then?
2) The tour will hopefully get support for DUB packages (#27) - will the new DPaste be able to handle this as well?

**Comment by wilzbach** [comment]
>> @nazriel do you have an API that we could use? I guess the only way is that we (or the client via CORS) sends you a POST request and you reply with the URL to the newly created DPaste? Or do you have a better idea?
  Using GET would be a lot simpler, but this sadly has a restriction of 2K chars.
  http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

> Ping @nazriel

Friendly Pong

**Comment by wilzbach** [comment]
We now have our own editor replacement at run.dlang.io
