### ISSUE TITLE
Give the full-page editor its own domain name

### ISSUE THREAD

**Issue by CyberShadow** [dlang-tour/core#562]
If the editor is to be expanded in scope outside the tour (it's currently already used for dlang.org runnable examples, and will probably supplant DPaste), it would be good to promote it to its own "service", with its own dlang.org (or dlang.io) subdomain.

**Comment by wilzbach** [comment]
Good idea - this was on my TODO list already.
How about simply `editor.dlang.io`?

**Comment by CyberShadow** [comment]
Yep, I guess one can come up with any number of names:

- try.dlang.tld
- play.dlang.tld
- edit.dlang.tld
- paste.dlang.tld
- run.dlang.tld
- share.dlang.tld
- ide.dlang.tld
- code.dlang.tld
- online.dlang.tld
- compile.dlang.tld
- explore.dlang.tld

There's probably a lot of arguments you can make in favor of or against these, especially considering possible future directions of the site (merging with DPaste / asm.dlang.org / d.godbolt.org/ explore.dgnu.org / etc.)

editor.dlang.io is fine IMO.

**Comment by wilzbach** [comment]
> Yep, I guess one can come up with any number of names:

Hehe I thought so, but let's better keep the discussion for other people in the future and do actual work :)

> editor.dlang.io is fine IMO.

Alrighty - after initially going with `editor.dlang.io` I pivoted to `run.dlang.io` -> https://github.com/dlang-tour/core/pull/563
