### ISSUE TITLE
Toolbar icons are stuck to the text

### ISSUE THREAD

**Issue by BBasile** [dlang-tour/core#569]
Needs some space ASAP.

![stucktexticon](https://user-images.githubusercontent.com/16154339/27905898-bcc1b3b4-6241-11e7-811a-79e836c670fa.png)

**Comment by ZombineDev** [comment]
https://github.com/dlang-tour/core/pull/570

**Comment by ZombineDev** [comment]
The dmd-beta failure is caused by https://issues.dlang.org/show_bug.cgi?id=17608.

**Comment by BBasile** [comment]
thanks.
