### ISSUE TITLE
Help select a more fitting icon for formatting

### ISSUE THREAD

**Issue by ZombineDev** [dlang-tour/core#572]
Currently we use the [play](http://fontawesome.io/icon/play/) FontAwesome icon for both the Run and the Format buttons:

![currently](https://user-images.githubusercontent.com/3475150/27953095-3a67787c-6313-11e7-820f-bc6af136949a.png)

( And after #571:

![after](https://user-images.githubusercontent.com/4370550/27940235-cac78c30-62c9-11e7-96a3-9ebe86b5fab1.png)
)

Can we find a more fitting icon? Here are some half-serious suggestions:
* http://fontawesome.io/icon/diamond/
* http://fontawesome.io/icon/magic/
* http://fontawesome.io/icon/i-cursor/
* http://fontawesome.io/icon/file-code-o/
* http://fontawesome.io/icon/cubes/
* http://fontawesome.io/icon/paint-brush/
* http://fontawesome.io/icon/gavel/
* http://fontawesome.io/icon/keyboard-o/

**Comment by wilzbach** [comment]
Of course it doesn't need to be FontAwesome.

Btw I like the magic one for format.

**Comment by ZombineDev** [comment]
Fixed in #571.
