### ISSUE TITLE
If you try >run with the default example you get an error if you choose "all".

### ISSUE THREAD

**Issue by EmTee70** [dlang-tour/core#623]
https://run.dlang.io/
```
Up to      2.052  : Failure with output: Fatal error: execvp failed (No such file or directory)
Since      2.054  : Success with output: Hello D
```
This might be what you want, but it is not what I would expect.

**Comment by wilzbach** [comment]
It is expected, we run the example against _all_ D compiler in existence and summarize the changes...

Maybe the option just needs a better name?

**Comment by EmTee70** [comment]
Thats ok, but "execvp failed" what does this mean? Was there a massive change from 2.052 to 2.054?
Just saw that this was 2011. https://dlang.org/changelog/ . 
Just checked that with write / not writeln it compiles for all versions.
Shouldn't it than be possible to select a certain DMD?

**Comment by wilzbach** [comment]
> Was there a massive change from 2.052 to 2.054?

Yes.

> Shouldn't it than be possible to select a certain DMD?

The sole reason for this feature is to quickly judge whether a bug is a regression or maybe has already been fixed.
Have a look at these examples:

https://run.dlang.io/is/ckNT9i
https://run.dlang.io/is/UZhQDh

I hope they explain why this feature is useful. I just think it has a misleading name. Would sth. like "Regression finder (all)"  be better?

**Comment by EmTee70** [comment]
Yes, thats very cool! Thank you for your explanation.

**Comment by wilzbach** [comment]
The button has now been renamed to "All D compilers (2.060 - latest)".
I hope that makes it more clear -> I will close this now. Please feel free to open new issues if you have any other issues with the DTour or run.dlang.io ;-)
