### ISSUE TITLE
run.dlang.io "Dlang-Tour" toolbar button does not link to the tour

### ISSUE THREAD

**Issue by BBasile** [dlang-tour/core#625]
In addition to fixing this i suggest to add a "Run" button when on dlang tour (not displayed anymore when on run.dlang.io)

**Comment by wilzbach** [comment]
> i suggest to add a "Run" button when on dlang tour (not displayed anymore when on run.dlang.io)

I'm sorry. What do you mean by this?

**Comment by BBasile** [comment]
I suggested:
- when you're on the tour main page, shows a Run button.
- when you're on the Run page, shows a Dlang-Tour button

But just the label as done in the PR fixes the issue.
