### ISSUE TITLE
Command-line arguments

### ISSUE THREAD

**Issue by zorael** [dlang-tour/core#635]
The `run.dlang.io` default Hello World uses a main signature that takes a `string[]` parameter.

```d
import std.stdio;
void main(string[] args)
{
    writeln("Hello D");
}
```
However, there is no way to supply any arguments, which was possible with dpaste (which also supported standard input).

An enhancement request is to either add the possibliity of entering such, much like we can now enter compiler arguments, or to change the example's signature to `void main()` to be less confusing.

**Comment by wilzbach** [comment]
> However, there is no way to supply any arguments, which was possible with dpaste (which also supported standard input).

FYI: the backend does support `stdin` (the frontpage example on dlang.org) need this.

> An enhancement request is to either add the possibliity of entering such, much like we can now enter compiler arguments

I didn't add this to run.dlang.io because imho in 99% of all cases only a need for compile-time arguments and it adds more noise to the UI.

> or to change the example's signature to void main() to be less confusing.

I went with this in #636 ;-)
Thanks a lot for the input!
