### ISSUE TITLE
Tours for DUB packages

### ISSUE THREAD

**Issue by 9il** [dlang-tour/core#674]
Currently we can place only a single example for a DUB package. It would be nice to have a tour per package, at least for math related stuff.

**Comment by wilzbach** [comment]
We could simply add it as a new language?
Languages are completely independent as they use their own index.yml files.

And if wanted we can use subdomains like tour.dlang.science or whatever works best.
Would that work?

**Comment by 9il** [comment]
Awesome! One yml for all mir packages should be fine. Please let me know how I can pay for subdomain and server or transfer the payment to you.

**Comment by 9il** [comment]
I have used https://www.gandi.net previously

**Comment by wilzbach** [comment]
Oh I already own `dlang.science` - at Namecheap they had an offer: 5 years for 5$ in total :)

I will get to creating a `mir` repo later today, but using it in "standalone" locally will essentially be

```
dub run dlang-tour -- -l <path-to-mir-language-repo>
```

**Comment by wilzbach** [comment]
@9il 

https://github.com/dlang-tour/mir is now online at

https://tour.dlang.org/tour/mir/welcome/welcome-to/mir

I simple copy/pasted the DUB examples for now. There's no restriction on the structure, i.e. the `index.yml` define which chapters and sections are loaded.

I might look into mapping https://tour.dlang.org/tour/mir/welcome/welcome-to/mir to mir.dlang.science, but I currently don't have enough time for this. Sorry.
