### ISSUE TITLE
"Contract programming" is mentioned without being defined/introduced

### ISSUE THREAD

**Issue by mziwisky** [dlang-tour/core#675]
https://tour.dlang.org/tour/en/basics/exceptions mentions the importance of avoiding contract programming for user-input, but contract programming hasn't been defined yet.  One might be able to infer from the following text that `assert` is related, but it's still not clear.  I think it would suffice to make the phrase a hyperlink to https://dlang.org/spec/contracts.html

**Comment by wilzbach** [comment]
https://github.com/dlang-tour/english/pull/244 -  thanks a lot!
