### ISSUE TITLE
Syntax for annotations in the unittest example are wrong

### ISSUE THREAD

**Issue by mziwisky** [dlang-tour/core#676]
https://tour.dlang.org/tour/en/gems/unittesting has an example of

```
unittest @safe @nogc nothrow pure
{
    assert(myAbs() == 1);
}
```

but this doesn't compile with `dmd -unittest`.  It looks like the `unittest` keyword should actually come after the annotations, according to https://dlang.org/spec/unittest.html#attributes_unittest

**Comment by wilzbach** [comment]
Thanks! -> https://github.com/dlang-tour/english/pull/243
