### ISSUE TITLE
Spanish translations are not automatically deployed after merge

### ISSUE THREAD

**Issue by diegolagoglez** [dlang-tour/core#687]
More than 20 hours after [the merge](https://github.com/dlang-tour/spanish/pull/21), Spanish translation updates are not present/deployed in the [Spanish D Language Tour page](https://tour.dlang.org/tour/es).

**Comment by wilzbach** [comment]
Hmm, looks like the docker binary was correctly updated:

https://hub.docker.com/r/dlangtour/core/tags

Will investigate.

**Comment by wilzbach** [comment]
> Will investigate.

You have no `index.yml` file, hence the files weren't listed.

**Comment by wilzbach** [comment]
No sorry - there's one: https://github.com/dlang-tour/spanish/blob/master/gems/index.yml

**Comment by wilzbach** [comment]
-> https://github.com/dlang-tour/spanish/pull/24

**Comment by diegolagoglez** [comment]
Ups! My fault.

Thanks very much!
