### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by icy** [dlang-tour/core#704]
May I start a new experimental translation of Dlang-Tour? I can initial with some sections and I'll allocate more resources if that will be going well.

Thanks a lot.

**Comment by wilzbach** [comment]
Cool!
I created a repo, setup Travis, created a GitHub team and invited you (let us know if there are more Vietnamese D enthusiasts who want to help - it often helps a lot to have a reviewer.)

https://github.com/dlang-tour/vietnamese

This adds it to the core repo: https://github.com/dlang-tour/core/pull/706 (as submodule).

We're currently having issues with auto-deploy, but normally changes to the markdown content will be deployed within ~10 minutes.
However, only markdown documents listed in the YAML file be displayed.

You can directly preview your translation locally with sth. like:

```
dub fetch dlang-tour
dub run dlang-tour --override-config="vibe-d:tls/openssl-1.1" -- -l .
```

Happy translating!

PS:If you ever run into issues, just give us a ping here or mention @dlang-tour/base

**Comment by icy** [comment]
Thank you for your quick support @wilzbach. 

Should we close this ticket or wait until any part of the tour is translated?

**Comment by icy** [comment]
That's awesome. Thanks @wilzbach . Can I handle the PR on the project by myself? (I have merged the PR #3 I should have asked you about this )

**Comment by icy** [comment]
@wilzbach I have merged a few PRs however the page (https://tour.dlang.org/tour/vi) hasn't been updated. Any ideas? Thanks.

**Comment by wilzbach** [comment]
>  Any ideas? Thanks.

https://github.com/dlang-tour/vietnamese/blob/master/welcome/index.yml

> However, only markdown documents listed in the YAML file be displayed.

**Comment by icy** [comment]
Oh I didn't know that. Thanks a lot  :)

**Comment by wilzbach** [comment]
>  Can I handle the PR on the project by myself?

Sorry for not seeing your comment. Well, ideally someone else would review it, but given that I don't know anyone who speaks Vietnamese, I think you did the right thing by merging it.

BTW you want to add Vietnamese to this page: https://tour.dlang.org/tour/en/welcome/languages (it's ok if it's only partially translated, but it helps people to find it).

**Comment by icy** [comment]
I will update that page very soon. Thanks again :)

**Comment by icy** [comment]
> Sorry for not seeing your comment. Well, ideally someone else would review it, but given that I don't know anyone who speaks Vietnamese, I think you did the right thing by merging it.

I will invite some people here to to join the project. I haven't known any people who is using D in my city :)
