### ISSUE TITLE
-checkaction=[...] option prevents output

### ISSUE THREAD

**Issue by veelo** [dlang-tour/core#722]
Details: https://issues.dlang.org/show_bug.cgi?id=19711

**Comment by wilzbach** [comment]
Fixed by https://github.com/dlang-tour/core-exec/pull/44 and https://github.com/dlang-tour/core-exec/pull/45

It's deployed now (though there's a bit of a cache for old results): https://run.dlang.io/is/vc6dFM

**Comment by veelo** [comment]
Thanks!
