### ISSUE TITLE
Add llvm-symbolizer to the path in run.dlang.org image

### ISSUE THREAD

**Issue by JohanEngelen** [dlang-tour/core#733]
When using Address Sanitizer, location information is not available in the output:
https://run.dlang.io/is/H0nQKi

This can be solved by adding `llvm-symbolizer` to the path. Probably that tool is not installed by default in the docker image, so needs installation first. Should be part of the `llvm` package.

background info: https://clang.llvm.org/docs/AddressSanitizer.html#symbolizing-the-reports

**Comment by JohanEngelen** [comment]
See also: https://stackoverflow.com/questions/38079761/why-does-asan-symbolizer-path-no-longer-work-with-version-adorned-binaries

**Comment by JohanEngelen** [comment]
@wilzbach Do you think you can fix this? Thanks!

**Comment by Geod24** [comment]
I think it should just be a matter of adding it [here](https://github.com/dlang-tour/core-exec/blob/45982255d71905853b25c2355f4beb830770b4dc/Dockerfile#L5-L17)

**Comment by JohanEngelen** [comment]
@Geod24 Thanks! https://github.com/dlang-tour/core-exec/pull/53
