### ISSUE TITLE
Default generated code uses a lot of Intel 387 instructions, not SSE2+

### ISSUE THREAD

**Issue by baryluk** [dlang-tour/core#752]
I was exploring some code in ldc and dmd using the website, and found out even a simple code would create a ton of old-FPU style instructions, even with some flags to try to force it to nod to it:

https://run.dlang.io/is/GakIJp

Maybe it is related to the pow, and the silly fact that it does receive the `real` instead of `double` ?

Or maybe the dmd and ldc used on the site by default defaults to 32-bit mode somehow?

**Comment by Geod24** [comment]
Looks like https://issues.dlang.org/show_bug.cgi?id=18559 ?

**Comment by baryluk** [comment]
Yes, you are right. This is an issue with the phobos and the compiler, not the dlang-tour.
