### ISSUE TITLE
The unexcepted 404 code

### ISSUE THREAD

**Issue by PeterlitsZo** [dlang-tour/core#762]
As what I issue at [here](https://github.com/dlang-tour/english/issues/349) but without any reply, I want know why it report this:
```
Access Error: 404 -- Not Found
Cannot locate document: /
```
when I access `127.0.0.1:8080`, what the url the server want to get or just I follow the wrong step?

**Comment by PeterlitsZo** [comment]
By the way, I find that the chinese version is too early(2017), what is the best way to update it by the latest english document.
`>_<`

**Comment by Geod24** [comment]
@PeterlitsZo : To update the documentation, make PRs to https://github.com/dlang-tour/chinese
You can see it used as submodule here: https://github.com/dlang-tour/core/tree/master/public/content

**Comment by PeterlitsZo** [comment]
I know what HAPPEND on my laptop!!!
I run the server on the `WSL 2` but the `8080` port has been occupied by some server on the `Windows`. That why I get the 404 code!
I change the `config.yml` and then rerun, then all thing goes well as I think! I hope this is helpful if anybody get the same 404 code~

**Comment by PeterlitsZo** [comment]
> @PeterlitsZo : To update the documentation, make PRs to https://github.com/dlang-tour/chinese
> You can see it used as submodule here: https://github.com/dlang-tour/core/tree/master/public/content

Thanks~

**Comment by Geod24** [comment]
Since it's user error, can you close ? Thanks!
