### ISSUE TITLE
Broken hyperlink readf documentation

### ISSUE THREAD

**Issue by HuskyNator** [dlang-tour/core#764]
The format argument for the readf function found at https://dlang.org/phobos/std_stdio.html#.File.readf redirects to a nonexistant 'format string' page.

**Comment by PetarKirov** [comment]
> Edit: seems this is the wrong place, my mistake, sorry.

No worries - do let us know if there's something we can improve on our side. Also for issues and suggestions related to the content itself,  consider opening an issue on the language specific repos, e.g. https://github.com/dlang-tour/english
