### ISSUE TITLE
run.dlang.io: dmd-nightly not using nightly build

### ISSUE THREAD

**Issue by dkorpel** [dlang-tour/core#770]
Evidenced by selecting dmd-nightly and running this:
```D
pragma(msg, __VERSION__);
```
Which prints `2098L`, while dmd-beta prints `2099L`

**Comment by MoonlightSentinel** [comment]
It's using the nightly build but the newer images hang when compiling D code (for some unknown reason). That causes `run.dlang.io` to retain the latest working image.

**Comment by PetarKirov** [comment]
The nightly should be fixed now. I opened a PR with various CI/CD implevemnts: https://github.com/dlang-tour/core/pull/772
